//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZecaTrocosMercariEurohack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hint
    {
        public int Id { get; set; }
        public string CategoryIdentifier { get; set; }
        public string HintText { get; set; }
        public string CsFields { get; set; }
    }
}
