//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZecaTrocosMercariEurohack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HintModifier
    {
        public int Id { get; set; }
        public int HintId { get; set; }
        public int ModifierId { get; set; }
    
        public virtual Hint Hint { get; set; }
        public virtual Modifier Modifier { get; set; }
    }
}
