//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZecaTrocosMercariEurohack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnowledgeDbEntities : DbContext
    {
        public KnowledgeDbEntities()
            : base("name=KnowledgeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hint> Hints { get; set; }
        public virtual DbSet<HintModifier> HintModifiers { get; set; }
        public virtual DbSet<Modifier> Modifiers { get; set; }
    }
}
